### PR TITLE
Fixed chunk change event, loading database =\ and cosmetics for LightAPI =)

### PR DESCRIPTION
**Pull request by Qveshn**
Fixed loading of the database. Back to single thread =(
A separate task for LightAPI has been removed

### CODE REVIEW

**Comment by Ste3et** [comment]
PacketType.Play.Client.POSITION_LOOK & PacketType.Play.Client.POSITION is a async event you can send a protocollib packet async to the this make no problems the only thing you can not do is block changing world loading or entity spawning over the bukkit API, i call the addLight async on loading this is the reason i need the Bukkit sync shedular, i do not know why i cannot update the chunks async.

**Comment by Qveshn** [comment]
When your plugin called updatePlayerView then there were error on BungeeCord
When I changed it to call via getScheduler.runTask then there are no errors on BungeeCord

**Comment by Qveshn** [comment]
Is it my error that Travis CI build could not complete?
`[ERROR] Failed to execute goal on project FurnitureLib: Could not resolve dependencies for project me.imcj:FurnitureLib:jar:1.6.2-snapshot-01: Failed to collect dependencies at com.comphenix.protocol:ProtocolLib:jar:4.0.1: Failed to read artifact descriptor for com.comphenix.protocol:ProtocolLib:jar:4.0.1: Could not transfer artifact com.comphenix.protocol:ProtocolLib:pom:4.0.1 from/to vault-repo `

**Comment by PhanaticD** [comment]
just saying pretty much everything in the bukkit api needs to be done sync

**Pull request closed without merging**
